#!/usr/bin/env bash

#
# In-place substitution and resolution
# of AWS Security Group IDs to Security Group Names
# piped from STDIN
# 
# example usage:   
#
#   bash$: echo "Your group is sg-12334678" | sg-convert
#   Your group is my-group-name
#

REGION="${AWS_DEFAULT_REGION:-us-east-1}"
OUTPUT="${AWS_DEFAULT_OUTPUT:-text}"

function getName() {
  aws ec2 describe-security-groups \
    --group-ids "${@}" \
    --query 'SecurityGroups[].GroupName' \
    --region "${REGION}" \
    --output "${OUTPUT}"
} 

sed -E 's#(.*)(sg-[a-z0-9]{8})(.*)#"\1$(getName \2)\3"#' < "${1:-/dev/stdin}" |
while read -r line; do
  eval echo "$line"
done
