FROM 502718739766.dkr.ecr.us-east-1.amazonaws.com/amazonlinux2:agent

RUN yum -y install docker gcc java-1.8.0-openjdk-devel \
  && usermod -a -G docker jenkins \
  && yum clean all \
  && rm -rf /var/cache/yum

USER jenkins

ENTRYPOINT ["jenkins-slave", "-workDir", "/home/jenkins/workspace"]
